const express = require('express');
const { Pool } = require('pg');
const cors = require('cors');
const https = require('https');

const app = express();
// 增强CORS配置
app.use(cors({
  origin: '*',
  methods: ['GET', 'POST'],
  allowedHeaders: ['Content-Type']
}));
app.use(express.json());

// 连接 Render PostgreSQL（增加连接配置）
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
  idleTimeoutMillis: 30000,
  connectionTimeoutMillis: 20000,
  max: 20 // 最大连接数
});

// 测试数据库连接（增加重连逻辑）
async function testDbConnection() {
  let retries = 3;
  while (retries > 0) {
    try {
      const client = await pool.connect();
      console.log('✅ 数据库连接成功');
      client.release();
      return true;
    } catch (err) {
      retries--;
      console.error(`❌ 数据库连接失败（剩余重试${retries}次）：`, err.message);
      await new Promise(resolve => setTimeout(resolve, 2000));
    }
  }
  throw new Error('数据库连接重试失败，请检查DATABASE_URL是否正确');
}

// 初始化分数表（兼容Render PostgreSQL）
async function initTable() {
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS scores (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id VARCHAR(50) NOT NULL,
        score INT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `);
    console.log('✅ 数据表初始化成功（或已存在）');
  } catch (err) {
    console.error('❌ 表初始化失败：', err.message);
    throw err; // 抛出错误，让启动流程终止
  }
}

// 1. 提交分数接口（增加错误捕获+日志）
app.post('/submit', async (req, res) => {
  console.log('📥 收到提交请求：', req.body);
  const { user_id, score } = req.body;

  // 校验参数
  if (!user_id || score === undefined || isNaN(score)) {
    const errMsg = '参数错误：user_id不能为空，score必须是数字';
    console.error('❌', errMsg);
    return res.status(400).json({ 
      success: false, 
      error: errMsg 
    });
  }

  try {
    const result = await pool.query(
      'INSERT INTO scores (user_id, score) VALUES ($1, $2) RETURNING *',
      [user_id, parseInt(score)]
    );
    console.log('✅ 数据插入成功：', result.rows[0]);
    res.status(201).json({
      success: true,
      data: result.rows[0]
    });
  } catch (err) {
    console.error('❌ 插入数据失败：', err.message);
    res.status(500).json({ 
      success: false, 
      error: '服务器内部错误：' + err.message 
    });
  }
});

// 2. 获取排行榜接口
app.get('/ranking', async (req, res) => {
  console.log('📥 收到排行榜请求');
  try {
    const result = await pool.query(
      'SELECT user_id, score FROM scores ORDER BY score DESC, created_at ASC LIMIT 100'
    );
    console.log('✅ 返回排行榜数据：', result.rows.length, '条');
    res.json(result.rows);
  } catch (err) {
    console.error('❌ 查询排行榜失败：', err.message);
    res.status(500).json([]);
  }
});

// 3. 健康检查
app.get('/health', (req, res) => {
  res.send('ok');
});

// 防休眠函数
const selfUrl = 'https://da-di-quizhou-duan.onrender.com/health';
function keepAlive() {
  https.get(selfUrl, (res) => {
    console.log(`💓 防休眠心跳：${new Date()}，状态码：${res.statusCode}`);
  }).on('error', (err) => {
    console.error(`💔 防休眠心跳失败：${new Date()}，错误：${err.message}`);
  });
}

// 启动流程（确保数据库连接成功后再启动）
async function startServer() {
  try {
    console.log('🚀 开始启动服务...');
    // 1. 测试数据库连接
    await testDbConnection();
    // 2. 初始化数据表
    await initTable();
    // 3. 启动服务
    const PORT = process.env.PORT || 3000;
    app.listen(PORT, () => {
      console.log(`🚀 服务已启动，端口：${PORT}`);
    });
    // 4. 启动防休眠
    keepAlive();
    setInterval(keepAlive, 600000);
  } catch (err) {
    console.error('❌ 服务启动失败：', err.message);
    process.exit(1); // 终止进程，Render会自动重启
  }
}

// 执行启动流程
startServer();

// 捕获未处理的异常
process.on('uncaughtException', (err) => {
  console.error('❌ 未捕获的异常：', err.message);
  process.exit(1);
});

process.on('unhandledRejection', (err) => {
  console.error('❌ 未处理的Promise拒绝：', err.message);
  process.exit(1);
});
